# Generated by Django 5.0.6 on 2024-07-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_selection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='age',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='gender',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
