# Generated by Django 5.0.6 on 2024-07-06 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_selection', '0002_alter_patientdetails_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdetails',
            name='email',
        ),
    ]
