# Generated by Django 5.0.6 on 2024-06-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_selection', '0002_timeslot_approved_by_timeslot_booked_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='booked_by',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='reschedule_requested',
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reschedule_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(max_length=14),
        ),
    ]
