# Generated by Django 5.0.6 on 2024-07-08 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_selection', '0003_remove_patientdetails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctornonavailability',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_availability', to='appointment_selection.doctor'),
        ),
    ]
