# Generated by Django 5.0.6 on 2024-06-21 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_selection', '0003_remove_timeslot_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorNonAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('blood_group', models.CharField(blank=True, max_length=3)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['start_time'], name='appointment_start_t_6ceaf5_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['end_time'], name='appointment_end_tim_4e1505_idx'),
        ),
        migrations.AddField(
            model_name='doctornonavailability',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment_selection.doctor'),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointment_selection.patient'),
        ),
    ]
