# Generated by Django 5.0.6 on 2024-06-21 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_selection', '0004_doctornonavailability_patientdetails_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctornonavailability',
            options={'verbose_name_plural': 'Doctor Non Availability'},
        ),
        migrations.AlterModelOptions(
            name='patientdetails',
            options={'verbose_name_plural': 'Patient Details'},
        ),
    ]
