# Generated by Django 5.0.6 on 2024-07-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_selection', '0004_alter_doctornonavailability_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctornonavailability',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctornonavailability',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
