# Generated by Django 5.0.6 on 2024-07-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_selection', '0005_alter_doctornonavailability_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctornonavailability',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='doctornonavailability',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
