# Generated by Django 5.0.6 on 2024-06-21 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_selection', '0006_rename_day_doctornonavailability_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctornonavailability',
            old_name='end_date',
            new_name='day',
        ),
        migrations.RemoveField(
            model_name='doctornonavailability',
            name='start_date',
        ),
    ]
