# Generated by Django 5.0.6 on 2024-06-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_selection', '0007_rename_end_date_doctornonavailability_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctornonavailability',
            old_name='day',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='doctornonavailability',
            name='start_date',
            field=models.DateField(default='2024-01-22'),
            preserve_default=False,
        ),
    ]
