# Generated by Django 5.0.6 on 2024-06-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_selection', '0009_remove_doctornonavailability_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctornonavailability',
            name='end_date',
            field=models.DateField(default='2024-06-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctornonavailability',
            name='end_time',
            field=models.TimeField(default='10:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctornonavailability',
            name='start_date',
            field=models.DateField(default='2024-06-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctornonavailability',
            name='start_time',
            field=models.TimeField(default='10:00:00'),
            preserve_default=False,
        ),
    ]
