# Generated by Django 5.0.6 on 2024-07-14 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_selection', '0010_timeslot_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointment_selection.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment_selection.patient')),
            ],
        ),
    ]
