# Generated by Django 5.0.6 on 2024-07-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_selection', '0012_delete_pastappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='zip_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
